### PR TITLE
Correction to documentation in README.md

### PR DESCRIPTION
**Pull request by djgraff209**
Correcting alt_conf specification to include '[]' list definition.

### CODE REVIEW

**Comment by dhoer** [comment]
What does rubocop do with that?  I think rubocop will remove them since they are not needed.

**Comment by djgraff209** [comment]
Every time I tried running the resource without that it choked saying something to the effect that the argument count was expected to be 0..1 but received 2. I'll check it again in my test environment. I'm running under chef 12.5 in a vm under windows so I don't know if I can run test kitchen yet. I'll see what I can work out next week and get back to you

**Comment by djgraff209** [comment]
Scratch last comment ... I'll check it with rubocop as I don't need test kitchen

**Comment by djgraff209** [comment]
Ran rubocop against my recipe that uses the resource and (after a bunch of whitespace indent issues) it did not bark about the array specifier. Is that what you were asking? If not please provide some direction on that.

**Comment by dhoer** [comment]
Yes, that is what I was asking.  Thanks

**Pull request merged**
