### PR TITLE
Updated unit tests now that multiple migrations will run.

### PR DESCRIPTION
**Pull request by djgraff209**
Corrected unit tests now that multiple migrations will run.

Follow on to #26

### CODE REVIEW

**Comment by djgraff209** [comment]
All tests passing

**Comment by djgraff209** [comment]
Done & done - I look forward to the update - this cookbook saved my butt a SIGNIFICANT amount of work.

**Comment by dhoer** [comment]
Good to hear.  Thanks for the PR!

**Comment by djgraff209** [comment]
Should I have bumped the patch rev number in the metadata.rb?

**Pull request merged**
